version: "3.9"

services:
  wind-farm-webapp:
    build:
      context: ./wind_farm_webapp
      args:
        REACT_APP_WIND_FARM_API: wind-farm-service
    ports:
      - "3000:80"
    depends_on:
      - wind-farm-service
    volumes:
      - ./wind_farm_webapp/src:/app/src

  wind-farm-service:
    build: ./wind_farm_service
    ports:
      - "8080:8000"
    depends_on:
      - wind-farm-sqldb
    environment:
      - MAIN_DB_HOST=wind-farm-sqldb
      - MAIN_DB_PORT=5432
      - MAIN_DB_DATABASE=wind_farm
      - MAIN_DB_USER=wind-farm-dev
      - MAIN_DB_PASSWORD=dev-pwd-to-be-replaced-by-secrets!
    volumes:
      - ./wind_farm_service/src:/app/src
      - ./raw-data:/app/raw-data

  wind-farm-sqldb:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wind_farm
      - POSTGRES_USER=wind-farm-dev
      - POSTGRES_PASSWORD=dev-pwd-to-be-replaced-by-secrets!
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:
    driver: local
