# Generated by Django 4.1.7 on 2023-03-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('acquisition_date', models.DateField(null=True)),
                ('number_3l_code', models.CharField(max_length=3)),
                ('deal_type_id', models.CharField(max_length=10)),
                ('group_id', models.CharField(max_length=10)),
                ('status_id', models.CharField(max_length=20)),
                ('company_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTG',
            fields=[
                ('wtg_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_id', models.CharField(max_length=20)),
                ('region_id', models.CharField(max_length=50)),
                ('kw', models.IntegerField()),
                ('hub', models.IntegerField()),
                ('rotor', models.IntegerField()),
                ('altitude', models.IntegerField(null=True)),
                ('cod', models.DateField(null=True)),
                ('zip_code', models.IntegerField()),
                ('wgs_84_north', models.FloatField()),
                ('wgs_84_east', models.FloatField()),
                ('gauss_krueger_zone', models.IntegerField()),
                ('gauss_krueger_north', models.FloatField()),
                ('gauss_krueger_east', models.FloatField()),
                ('town_id', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
        ),
    ]
